block_labels = ["wip"]
delete_merged_branches = true
status = [
    "Rustfmt",
    "ci (1.69.0, stm32h503)",
    "ci (1.69.0, stm32h562)",
    "ci (1.69.0, stm32h563)",
    "ci (1.69.0, stm32h573)",
    "ci (stable, stm32h503)",
    "ci (stable, stm32h562)",
    "ci (stable, stm32h563)",
    "ci (stable, stm32h573)",
]
