[package]
name = "stm32h5xx-hal"
version = "0.0.0"
edition = "2021"
authors = [
    "Edwin Svensson <stm32h5xxhal@olback.net>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
