on:
    pull_request:
    push:
      branches: [master]

name: Clippy

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install thumb8 rust target
      run: rustup target add thumbv8m.main-none-eabihf
    - name: Cargo clippy
      run: cargo clippy --examples --target thumbv8m.main-none-eabihf --features=rt,stm32h503 -- -D warnings
